### ISSUE TITLE
Adding additional sensors/support for battery inverter

### ISSUE THREAD

**Issue by HartmutHartmann** [eddso/ha_sma_speedwire#1]
Added the integration to HA yesterday, seems to work well so far. 

Now I would like to add more sensors, for example to see dc power per string.
Additionally I do have a battery inverter which I would like to connect as well. The integration seems to connect initially, but reports 'Failed to set up' as soon as the inverter is added(didn't try logger yet). I also tried the 'test.py' which connects to both inverters just fine and reports correct data.

Unfortunately I have no experience writing Python or HA integrations. Any hints on which parts of the code need to be edited would be appreciated.

Edit: restarted Homeassistant, now the battery inverter seems to be fine, no more error...

**Comment by eddso** [comment]
- `sma_speedwire.py`: library to commulicate with SMA inverter
   - `COMMAND_LIST`: extend with commands to read from inverter, check https://github.com/Rincewind76/SMAInverter
   - `self.sensors`: extend list of sensors
   - `def _fetch(self, command)`: extend parser to parser added command responses and fill self.sensors
   - `def update(self)`: call added command
- `sensor.py`: HA sensor
   - `def __init__(self, coordinator, device, sensor)`: extend wit your added sensors. Check here https://developers.home-assistant.io/docs/core/entity/sensor/

contact me, mb i can help you.
